# fly.toml app configuration file generated for mongo2 on 2023-05-31T10:09:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "gru"

[[mounts]]
  source = "mongo_data"
  destination = "/data"

[checks]
  [checks.role]
    port = 5500
    type = "http"
    interval = "5s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "1s"
    method = "get"
    path = "/flycheck/vm"
