#!/bin/sh

command=$(cat << EOF
db.createUser(
  {
    user: "$MONGO_INITDB_ROOT_USERNAME",
    pwd: "$MONGO_INITDB_ROOT_PASSWORD",
    roles: [ 
      'root'
    ]
  }
)
EOF
)

mongosh admin --eval "$command"